### ISSUE TITLE
Typerror in DefectDojoAPI call

### ISSUE THREAD

**Issue by feeltheajf** [DefectDojo/defectdojo_api#17]
### Description
DefectDojo fails to authenticate while parsing host address

### Environment
Python 3.6.6
defectdojo-api-1.1.4

### Steps to reproduce
```
from defectdojo_api import defectdojo

api = defectdojo.DefectDojoAPI('https://localhost:8000', '123', 'admin', debug=False)
```

### Result
File "/usr/local/lib/python3.6/dist-packages/defectdojo_api/defectdojo.py", line 37, in __init__
    if host.split('/') > 3:
TypeError: '>' not supported between instances of 'list' and 'int'

### Proposed fix
Change to 
```
len(host.split('/')) > 3:
```

**Comment by bakalor** [comment]
same issue, any fix planned?
