### ISSUE TITLE
pip3 does not have defectdojo_apiv2

### ISSUE THREAD

**Issue by chethanabhaskara** [DefectDojo/defectdojo_api#35]
I tried running this example defectdojo_api/examples/v2/dojo_ci_cd.py and it says cannot load module
ImportError: No module named defectdojo_apiv2. I saw that python package doesn't have the respective file. Could you please add it and publish the pip package again?

**Comment by valentijnscholten** [comment]
you can install from git like this
`pip install git+https://github.com/valentijnscholten/defectdojo_api/@acf0c0deb2dc5191d69f268412602bea5295a2e7`

or any other repo/commit

**Comment by chethanabhaskara** [comment]
Thank you, that's a helpful suggestion
