### ISSUE TITLE
Some apiv2 fields ignored when creating finding

### ISSUE THREAD

**Issue by fuzzah** [DefectDojo/defectdojo_api#61]
Some finding fields seem to change no matter what I specify. When I send my request, Defect Dojo server sends me response with data that actually gets uploaded, here are some changes/issues I've spotted at first glance:
1. "static_finding": field always becomes true
2. "dynamic_finding" -> always false
3. "reporter" -> always user id 1 (admin) (I'm uploading findings with user id 2, this user has Writer role on corresponding product)
4. "found_by" -> I get "field required" error, but **DefectDojoAPIv2.create_finding doesn't even take it as parameter**. It's unclear what to put in there, so I've been using user_id, until noticed that DD sends me "found_by": [<test_type_id>, <user_id>] in create_finding response. (means it should contain only test_type_id)

**Comment by valentijnscholten** [comment]
I noticed item 3 yesterday. Item 1 and 2 are probably set depending on the Test Type of the Test in which the finding is created. What Test Type is it?
Item 4 should contain the id of the Test_Type that found this finding. Please note the API docs contain examples which can be helpful.

**Comment by valentijnscholten** [comment]
oh I just noticed this issue is in the defect dojo api repository. Can you try your requests in the API docs of defect dojo (it has a try out function). This will help to determine if it's a defect dojo problem or in the api wrapper.

**Comment by fuzzah** [comment]
@valentijnscholten  thank you for rapid response!
I forgot to mention
defectdojo_api revision is 6f6d5e31dd2855e3e15d756b3a01a7dd8d77fdf9
defectdojo tag: 2.3.1

Test type is dynamic (I'm not using standard DD test type, I've created this one myself)

> 
> 
> oh I just noticed this issue is in the defect dojo api repository. Can you try your requests in the API docs of defect dojo (it has a try out function). This will help to determine if it's a defect dojo problem or in the api wrapper.

I will try that

**Comment by fuzzah** [comment]
So using APIv2 OpenAPI3 I've sent this payload to POST method of "findings":

```
{
  "test": 3016,
  "found_by": [
    141
  ],
  "title": "My API-testing issue title",
  "date": "2021-11-10",
  "cwe": 20,
  "severity": "Critical",
  "description": "My API-testing description",
  "impact": "Integrity",
  "references": "google.com",
  "active": true,
  "verified": true,
  "false_p": false,
  "is_mitigated": false,
  "duplicate": false,
  "numerical_severity": "S0",
  "line": 200,
  "file_path": "/path/to/source/file.cpp",
  "static_finding": false,
  "dynamic_finding": true,
  "unique_id_from_tool": "Segmentation fault in /path/to/source/file.cpp:200",
  "vuln_id_from_tool": "Segmentation fault",
  "publish_date": "2021-11-10",
  "reporter": 2
}
```

In response I've got this:

```
{
  "id": 35178,
  "notes": [],
  "test": 3016,
  "thread_id": 0,
  "found_by": [
    141
  ],
  "url": null,
  "tags": [],
  "push_to_jira": false,
  "title": "My API-testing Issue Title",
  "date": "2021-11-10",
  "sla_start_date": null,
  "cwe": 20,
  "cve": null,
  "cvssv3": null,
  "cvssv3_score": null,
  "severity": "Critical",
  "description": "My API-testing description",
  "mitigation": null,
  "impact": "Integrity",
  "steps_to_reproduce": null,
  "severity_justification": null,
  "references": "google.com",
  "is_template": false,
  "active": true,
  "verified": true,
  "false_p": false,
  "duplicate": false,
  "out_of_scope": false,
  "risk_accepted": false,
  "under_review": false,
  "last_status_update": "2021-11-10T08:45:14.457609Z",
  "under_defect_review": false,
  "is_mitigated": false,
  "mitigated": null,
  "numerical_severity": "S0",
  "last_reviewed": null,
  "line_number": null,
  "sourcefilepath": null,
  "sourcefile": null,
  "param": null,
  "payload": null,
  "hash_code": "c87580583f0b3db992944219f610c4dba052b557498c46d20c842c44852b0c7b",
  "line": 200,
  "file_path": "/path/to/source/file.cpp",
  "component_name": null,
  "component_version": null,
  "static_finding": true,
  "dynamic_finding": false,
  "created": "2021-11-10T08:45:14.439492Z",
  "scanner_confidence": null,
  "unique_id_from_tool": "Segmentation fault in /path/to/source/file.cpp:200",
  "vuln_id_from_tool": "Segmentation fault",
  "sast_source_object": null,
  "sast_sink_object": null,
  "sast_source_line": null,
  "sast_source_file_path": null,
  "nb_occurences": null,
  "publish_date": "2021-11-10",
  "duplicate_finding": null,
  "review_requested_by": null,
  "defect_review_requested_by": null,
  "mitigated_by": null,
  "reporter": 1,
  "last_reviewed_by": null,
  "sonarqube_issue": null,
  "endpoints": [],
  "endpoint_status": [],
  "reviewers": [],
  "files": []
}
```

Seems to be happening in DefectDojo itself, not in the API wrapper
(reporter id changed from 2 to 1, static_finding changed to true, dynamic_finding changed to false)

Test id 141 has the following settings:
![image](https://user-images.githubusercontent.com/60884276/141080734-d719a522-ecc4-4f2f-80a4-65a7ecb16fc8.png)

**Comment by fuzzah** [comment]
Some updates:
I've upgraded DD to 2.4.1

Tried same payload with APIv2 OpenAPI2 and APIv2 OpenAPI3, as well as via defectdojo_api library @ 6f6d5e31dd2855e3e15d756b3a01a7dd8d77fdf9
Tried flipping checkboxes in my test settings (Static tool, Dynamic tool, Active)
Same issue appeared in my every attempt (same response with changed fields "reporter", "static_finding", "dynamic_finding").

I've created issue in DefectDojo repository: https://github.com/DefectDojo/django-DefectDojo/issues/5417

**Comment by righel** [comment]
Having the same issue as described in item 4, no way to specify `found_by` using the **DefectDojoAPIv2.create_finding()** method.
