### ISSUE TITLE
Add support for Swagger

### ISSUE THREAD

**Issue by GraoMelo** [DefectDojo/defectdojo_api#84]
Hello, everyone, thank you very much for maintaining the DefectDOJO project. I have been using it a lot, congratulations on the excellent work.

I would like to contribute by suggesting that, if possible, support for Swagger be added for the API. It is much easier to test using Swagger.

[Swagger.io - Getting Started](https://swagger.io/tools/open-source/getting-started/)

**Comment by mtesauro** [comment]
You can get a swagger/OpenAPI spec file already in any running DefectDojo by looking at the API page:

![image](https://github.com/DefectDojo/defectdojo_api/assets/3422419/aff7a461-7a62-40e6-b054-92239dc90bdb)
 
then

![image](https://github.com/DefectDojo/defectdojo_api/assets/3422419/968e6de7-47f8-4e51-a756-ee9ddf3c1455)

were you looking for something else?

**Comment by Liamhhhhh** [comment]
> You can get a swagger/OpenAPI spec file already in any running DefectDojo by looking at the API page:
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/332970659-aff7a461-7a62-40e6-b054-92239dc90bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzM1NjcsIm5iZiI6MTcxNjQzMzI2NywicGF0aCI6Ii8zNDIyNDE5LzMzMjk3MDY1OS1hZmY3YTQ2MS03YTYyLTQwZTYtYjA1NC05MjIzOWRjOTBiZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDMwMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU3Y2NmNGRlMDE4MjFkZDY1YWI2ZDI0M2FhMzAwY2UwZjdmM2U3Y2YxY2ExNzNlNzhjNGVjMWNhZDk5YmE3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NY-8zL8bowPCnO3u5BOZ99Umz1x05Aa5v_ueZ6G4WZY)
> 
> then
> 
> ![image](https://private-user-images.githubusercontent.com/3422419/332970537-968e6de7-47f8-4e51-a756-ee9ddf3c1455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzM1NjcsIm5iZiI6MTcxNjQzMzI2NywicGF0aCI6Ii8zNDIyNDE5LzMzMjk3MDUzNy05NjhlNmRlNy00N2Y4LTRlNTEtYTc1Ni1lZTlkZGYzYzE0NTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMDMwMTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWVlMjUyYzIxMGZlY2M4ZWI5NDkzZWQ2N2M5ODUxZjZlYzBjYWVkNmI3MTRiYmU5Y2VmOWIwYzk5ZWY4NjBlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9etXaCQSHlF32uQ7WAYm7-qNEIO2y4ity0Sf4A-EK8g)
> 
> were you looking for something else?

Thank you for your guidance. I successfully tested it on [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1).

**Comment by GraoMelo** [comment]
This request has already been completed.
